![Numpy logo](images\numpy.png)

# NumPy Tutorials - PART 2: Functions

## Setup

### Install library

Run below command if NumPy is not already installed.
```cmd
pip install numpy
```
or
```cmd
pip3 install numpy
```

### Import Library

In [1]:
import numpy as np


print("NumPy version:", np.__version__)

NumPy version: 2.3.0


### Preface

1. `len()` always returns the total number of elements in first dimension.
2. NumPy functions can be applied as global functions: `np.function_name(my_array)` or as object methods `my_array.function_name()`.
3. `?` without invoking the function using paranthesis `()`, like `my_array.function_name?` or `np.function_name?`, returns its [docstring][1].

[1]: https://peps.python.org/pep-0257/#what-is-a-docstring

## Reshape

In [2]:
arr = np.arange(1, 13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [3]:
arr.shape

(12,)

#### Docstring

In [4]:
arr.reshape?

Docstring:
a.reshape(shape, /, *, order='C', copy=None)

Returns an array containing the same data with a new shape.

Refer to `numpy.reshape` for full documentation.

See Also
--------
numpy.reshape : equivalent function

Notes
-----
Unlike the free function `numpy.reshape`, this method on `ndarray` allows
the elements of the shape parameter to be passed in as separate arguments.
For example, ``a.reshape(10, 11)`` is equivalent to
``a.reshape((10, 11))``.
Type:      builtin_function_or_method

In [5]:
arr.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### Reshape cannot loose data

In [7]:
try:
    np.arange(1, 14).reshape(3, 4)

except ValueError as err:
    print("Error:", err)

Error: cannot reshape array of size 13 into shape (3,4)


#### Auto reshape using `-1`

In [8]:
arr.reshape(3, -1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
arr.reshape(-1, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
arr.reshape(-1, 12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [11]:
arr.reshape(12, -1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [12]:
try:
    arr.reshape(-1, -1)

except ValueError as err:
    print("Error:", err)

Error: can only specify one unknown dimension


## Transpose

In [13]:
# Create an array of length 12 containing elements from 1 to 12 and
# rearrange those elements to form a 3-rows X 4-columns matrix.
arr = np.arange(1, 13).reshape(3, 4)
print(arr)
print("\nShape:", arr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape: (3, 4)


In [14]:
# arr.transpose?

### Using `T` attribute

In [15]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [16]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Using `transpose` function

In [17]:
arr.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [18]:
np.transpose(arr)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [19]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Indexing

NumPy array can be indexed in three ways:

1. Explicit indexing: By passing separate list of row indexes and column indexes.
2. Slicing: Using colon `:` operator.
3. Fancy indexing or Masking: Using comparison operators (`<`, `>`, `==`, `>=`, `<=`, `!=`) on NumPy array.

### Explicit indexing

#### Case #1: Accessing single element

In [20]:
# Reshape array of length 12 to 3X4 matrix.
arr = np.arange(1, 13).reshape(3, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Different ways to access elements in 2D array. For example to access second row third element:

1. Second row index: 1
2. Third column index: 2

In [21]:
arr[1][2]

np.int64(7)

In [22]:
arr[1, 2]

np.int64(7)

#### Case #2: Accessing multiple elements

In [23]:
# Reshape array of length 16 to 4X4 matrix.
arr = np.arange(1, 17).reshape(4, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

```
arr[
    [list of row indices],
    [list of column indices],
]
```

In [24]:
arr[[1, 2]]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
arr[[1, 2, 3], [1, 0, 3]]

array([ 6,  9, 16])

### Slicing

In [26]:
arr = np.arange(1, 17).reshape(4, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

```
arr[row_index_start:row_index_end, column_index_start:column_index_end]
```

1. Default value for `row_index_start` is zero.
2. Default value for `column_index_start` is zero.
3. `row_index_end` is exclusive.
4. `column_index_end` is exclusive.

#### Row Slicing

##### Case #1: Default indexes

In [27]:
arr[:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

##### Case #2: Index within range

In [28]:
arr[0:4]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

##### Case #3: Index out of range

When only `row_index_start` is out of range:

In [29]:
arr[4:]

array([], shape=(0, 4), dtype=int64)

When only `row_index_end` is out of range:

In [30]:
arr[:5]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

##### Case #4: Negative indexes

In [31]:
arr[1:-2]

array([[5, 6, 7, 8]])

#### Column Slicing

##### Case #1: Default Indexes

In [32]:
arr[:, :]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

##### Case #2: Indexes within range

In [33]:
arr[:, 0:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

`column_index_end` is exclusive.

In [34]:
arr[:, 0:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

##### Case #3: Indexes out of range

In [35]:
arr[:, :5]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [36]:
np.arange(1, 15)[[0, -1, 2]]

array([ 1, 14,  3])

##### Case #4: Negative indexes

In [37]:
arr[:, -1:]

array([[ 4],
       [ 8],
       [12],
       [16]])

In [38]:
arr[:, -1:2]

array([], shape=(4, 0), dtype=int64)

### Fancy indexing / Masking

In [39]:
arr = np.arange(1, 17).reshape(4, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### Masking using single conditions

In [40]:
arr < 8

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

#### Masking using multi conditions

Multiple conditions can be applied using logical bitwise operators grouped in parentheses:
1. `&`: AND
2. `|`: OR
3. `~`: NOT
4. `^`: XOR
5. `>>`: Right Shift
6. `<<`: Left Shift

For example below mask has multiple conditions inside parentheses separated by `&` operator.

In [41]:
(arr > 7) & (arr < 14)

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True, False, False, False]])

#### Fetch data using Masking

In [42]:
mask = (arr > 7) & (arr < 14)
arr[mask]  # Apply mask on array

array([ 8,  9, 10, 11, 12, 13])

> **Note**:
>
> Fetching data (or filtering) using Masking always returns single dimensional array.

In [43]:
np.cumsum([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

## Axis

Before utilizing on different types of functions in NumPy, its important to understand the concept of **axis** w.r.t NumPy arrays.

##### TL;DR

**Axis represents the index of dimension in the shape**

### Axis in 1D Array

In [44]:
arr = np.array([0, 1, 2, 3])
arr.shape

(4,)

#### No Axis

In [45]:
np.sum(arr)

np.int64(6)

#### Axis Zero

In [46]:
np.sum(arr, axis=0)

np.int64(6)

#### Axis One

In [47]:
try:
    np.sum(arr, axis=1)

except np.exceptions.AxisError as err:
    print(err)

axis 1 is out of bounds for array of dimension 1


### Axis in 2D Array

In [48]:
arr = np.arange(1, 7).reshape(2, 3)
print(arr)
print("\nShape:", arr.shape)

[[1 2 3]
 [4 5 6]]

Shape: (2, 3)


#### No Axis

In [49]:
np.sum(arr)

np.int64(21)

#### Axis Zero

In [50]:
np.sum(arr, axis=0)

array([5, 7, 9])

#### Axis One

In [51]:
np.sum(arr, axis=1)

array([ 6, 15])

#### Axis Two

In [52]:
try:
    np.sum(arr, axis=2)

except np.exceptions.AxisError as err:
    print(err)

axis 2 is out of bounds for array of dimension 2


### Axis in 3D Array

In [53]:
arr = np.arange(1, 13).reshape(2, 2, 3)
print(arr)
print("\nShape:", arr.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Shape: (2, 2, 3)


#### No Axis

In [54]:
np.sum(arr)

np.int64(78)

#### Axis Zero

In [55]:
np.sum(arr, axis=0)

array([[ 8, 10, 12],
       [14, 16, 18]])

#### Axis One

In [56]:
np.sum(arr, axis=1)

array([[ 5,  7,  9],
       [17, 19, 21]])

#### Axis Two

In [57]:
np.sum(arr, axis=2)

array([[ 6, 15],
       [24, 33]])

#### Axis Three

In [58]:
try:
    np.sum(arr, axis=3)

except np.exceptions.AxisError as err:
    print(err)

axis 3 is out of bounds for array of dimension 3


## Mathematical Functions

Some common aggregation functions:

1. `np.sum()`: Calculates the sum of array elements.
1. `np.mean()`: Computes the arithmetic mean (average) of array elements.
1. `np.median()`: Determines the median value of array elements.
1. `np.min()`: Finds the minimum value within the array.
1. `np.max()`: Finds the maximum value within the array.

### `sum`

In [59]:
arr = np.arange(1, 7).reshape(2, 3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
arr.sum?

Docstring:
a.sum(axis=None, dtype=None, out=None, keepdims=False, initial=0, where=True)

Return the sum of the array elements over the given axis.

Refer to `numpy.sum` for full documentation.

See Also
--------
numpy.sum : equivalent function
Type:      builtin_function_or_method

#### No Axis

In [61]:
arr.sum()

np.int64(21)

#### Axis Zero

In [62]:
arr.sum(axis=0)

array([5, 7, 9])

#### Axis One

In [63]:
arr.sum(axis=1)

array([ 6, 15])

### `max`

In [64]:
arr = np.array(
    [
        [1, 6, 3, 8],
        [5, 2, 7, 4],
    ]
)
arr

array([[1, 6, 3, 8],
       [5, 2, 7, 4]])

In [65]:
arr.max?

Docstring:
a.max(axis=None, out=None, keepdims=False, initial=<no value>, where=True)

Return the maximum along a given axis.

Refer to `numpy.amax` for full documentation.

See Also
--------
numpy.amax : equivalent function
Type:      builtin_function_or_method

#### No Axis

In [66]:
arr.max()

np.int64(8)

#### Axis Zero

In [67]:
arr.max(axis=0)

array([5, 6, 7, 8])

#### Axis One

In [68]:
arr.max(axis=1)

array([8, 7])

## Logical Functions

https://numpy.org/doc/stable/reference/routines.logic.html

### Truth value testing

https://numpy.org/doc/stable/reference/routines.logic.html#truth-value-testing

#### `any`

In [69]:
ages = np.array([32, 16, 18, 24, 50])
ages

array([32, 16, 18, 24, 50])

##### `any` on filters

###### Option #1

In [70]:
ages > 18

array([ True, False, False,  True,  True])

In [71]:
np.any(ages > 18)

np.True_

###### Option #2

In [72]:
(ages < 12)

array([False, False, False, False, False])

In [73]:
(ages < 12).any()

np.False_

In [74]:
(ages > 12)

array([ True,  True,  True,  True,  True])

In [75]:
(ages > 12).any()

np.True_

##### `any` on Arrays

###### Case #1: Negative, Zero and Positive numbers

In [76]:
arr = np.array([-1, 0, 1, 2])
arr

array([-1,  0,  1,  2])

In [77]:
arr.any()

np.True_

###### Case #2: Zero and Negative numbers

In [78]:
arr = np.array([-2, -1, 0])
arr

array([-2, -1,  0])

In [79]:
arr.any()

np.True_

###### Case #3: Only Zeros

In [80]:
arr = np.array([0, 0, 0])
arr

array([0, 0, 0])

In [81]:
arr.any()

np.False_

#### `all`

In [82]:
ages = np.array([32, 16, 18, 24, 50])
ages

array([32, 16, 18, 24, 50])

##### `all` on filters

###### Option #1

In [83]:
ages > 18

array([ True, False, False,  True,  True])

In [84]:
np.all(ages > 18)

np.False_

###### Option #2

In [85]:
(ages > 12)

array([ True,  True,  True,  True,  True])

In [86]:
(ages > 12).all()

np.True_

In [87]:
(ages < 12)

array([False, False, False, False, False])

In [88]:
(ages < 12).all()

np.False_

##### `all` on Arrays

###### Case #1: Negative, Zero and Positive numbers

In [89]:
arr = np.array([-1, 0, 1, 2])
arr

array([-1,  0,  1,  2])

In [90]:
arr.all()

np.False_

###### Case #2: Zero and Negative numbers

In [91]:
arr = np.array([-2, -1, 0])
arr

array([-2, -1,  0])

In [92]:
arr.all()

np.False_

###### Case #3: Only Zeros

In [93]:
arr = np.array([0, 0, 0])
arr

array([0, 0, 0])

In [94]:
arr.all()

np.False_

## Aggregation Functions

https://numpy.org/doc/stable/reference/routines.sort.html

### `where`

#### `where` on 1D Array

In [95]:
arr = np.array([6, -2, 0, 8, 5, 0, 10])
arr

array([ 6, -2,  0,  8,  5,  0, 10])

In [96]:
np.where(arr < 5, 0, 1)

array([1, 0, 0, 1, 1, 0, 1])

In [97]:
np.where(arr < 5)

(array([1, 2, 5]),)

In [98]:
np.where(arr)

(array([0, 1, 3, 4, 6]),)

#### `where` on 2D Array

In [99]:
arr = np.arange(1, 17).reshape(4, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [100]:
np.where(arr < 9, 0, 1)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [101]:
arr = np.array(
    [
        [0, 1, 2],
        [3, 0, 4],
        [5, 6, 0],
    ]
)

In [102]:
np.where(arr)

(array([0, 0, 1, 1, 2, 2]), array([1, 2, 0, 2, 0, 1]))

### Sorting

In [103]:
arr = np.array([10, 6, 0, 5, 7, 1])
arr

array([10,  6,  0,  5,  7,  1])

In [104]:
arr.sort()
arr

array([ 0,  1,  5,  6,  7, 10])

> **Note**:
>
> NumPy uses Tim sort algorithm to sort elements in the array

#### Axis in Sorting

##### TL;DR

**Default value for axis in `np.sort` is -1, hence NumPy always sorts array by last dimension by default**

### Sorting on 1D Array

In [105]:
arr = np.array([16, 2, 13, 9])
arr

array([16,  2, 13,  9])

##### No Axis

In [106]:
np.sort(arr)

array([ 2,  9, 13, 16])

##### Axis Zero

In [107]:
np.sort(arr, axis=0)

array([ 2,  9, 13, 16])

##### Axis One

In [108]:
try:
    np.sort(arr, axis=1)

except np.exceptions.AxisError as err:
    print(err)

axis 1 is out of bounds for array of dimension 1


#### Sorting 2D Array

In [109]:
arr = np.array(
    [
        [16, 2, 13, 9],
        [1, 6, 17, 18],
        [4, 10, 7, 11],
        [13, 18, 5, 6],
    ]
)
arr

array([[16,  2, 13,  9],
       [ 1,  6, 17, 18],
       [ 4, 10,  7, 11],
       [13, 18,  5,  6]])

##### No Axis

In [110]:
np.sort(arr)

array([[ 2,  9, 13, 16],
       [ 1,  6, 17, 18],
       [ 4,  7, 10, 11],
       [ 5,  6, 13, 18]])

##### Axis Zero

In [111]:
np.sort(arr, axis=0)

array([[ 1,  2,  5,  6],
       [ 4,  6,  7,  9],
       [13, 10, 13, 11],
       [16, 18, 17, 18]])

##### Axis One

In [112]:
np.sort(arr, axis=1)

array([[ 2,  9, 13, 16],
       [ 1,  6, 17, 18],
       [ 4,  7, 10, 11],
       [ 5,  6, 13, 18]])

#### Sorting 3D Array

In [ ]:
arr = np.array(
    [
        [
            [16, 2, 9],
            [1, 6, 18],
            [4, 7, 11],
            [3, 18, 5],
        ],
        [
            [1, 4, 13],
            [6, 2, 10],
            [13, 5, 7],
            [6, 11, 9],
        ],
    ]
)
print(arr)
print("\nShape:", arr.shape)

##### No Axis

In [ ]:
np.sort(arr)

##### Axis Zero

In [ ]:
np.sort(arr, axis=0)

##### Axis One

In [ ]:
np.sort(arr, axis=1)

##### Axis Two

In [ ]:
np.sort(arr, axis=2)

##### Axis Three

In [ ]:
try:
    np.sort(arr, axis=3)

except np.exceptions.AxisError as err:
    print(err)

## Broadcasting

### What is Broadcasting?

https://numpy.org/doc/stable/user/basics.broadcasting.html#broadcasting

![NumPy Broadcasting](images\numpy_broadcasting.png)

Image source: https://mathematica.stackexchange.com/q/99171/110892

In [ ]:
def display_ndarray(name, array):
    """
    Function to display NumPy array.
    """
    print(f"\nArray {name}:")
    print(array)
    print("Shape:", array.shape)

In [ ]:
a = np.array(
    [
        [0],
        [10],
        [20],
        [30],
    ]
)
display_ndarray("A", a)

b = np.array([0, 1, 2])
display_ndarray("B", b)

display_ndarray("A + B", a + b)

### Rules for Broadcasting

1. If two arrays differ in the number of dimensions, the shape of one with fewer dimensions is padded with ones on its leading left side.
2. If the shape of two arrays does not match in any dimensions, the array with shape equal to 1 is stretched to match the other shape.

### Example

#### Problem statement

Given two arrays A and B,

1. Shape of Array A: `(8, 1, 6, 1)`
2. Shape of Array B: `   (7, 1, 5)`

Applying Broadcasting rules on A and B:

#### Solution

##### Applying Rule #1:

Since shape of array B has fewer dimension compared to array A, new dimension is added to array B on the left most side:

After applying Broadcasting rule #1 on A and B:

1. Unchanged shape of Array A: `(8, 1, 6, 1)`
2. New shape of Array B: `(1, 7, 1, 5)`

##### Applying Rule #2:

After applying rule #1, since the shape of both arrays does not match in any dimension, both arrays are stretched wherever their dimension is One.

After applying Broadcasting rule #2 on A and B:

1. New shape of Array A: `(8, 7, 6, 5)`
2. New shape of Array B: `(8, 7, 6, 5)`