![Numpy logo](images\numpy.png)

# NumPy Tutorials - PART 2: Functions

## Setup

### Install library

Run below command if NumPy is not already installed.
```cmd
pip install numpy
```
or
```cmd
pip3 install numpy
```

### Import Library

In [1]:
import numpy as np


print("NumPy version:", np.__version__)

NumPy version: 2.3.0


## Shallow vs Deep Copy

#### Shallow Copy in Python List

In [2]:
a = [1, 2, 3, 4]
b = a

a[1] = 100
b

[1, 100, 3, 4]

In [3]:
a is b

True

#### Deep Copy in Python List

In [4]:
a = [1, 2, 3, 4]
b = a[:]

a[1] = 100
b

[1, 2, 3, 4]

In [5]:
a is b

False

#### Shallow Copy in NumPy

In [6]:
a = np.array([1, 2, 3, 4])
b = a.reshape(2, 2)

a[1] = 100
b

array([[  1, 100],
       [  3,   4]])

In [7]:
a is b

False

In [8]:
np.shares_memory(a, b)

True

#### Deep Copy in NumPy

In [9]:
a = np.array([1, 2, 3, 4])
b = a + 0

a[1] = 100
b

array([1, 2, 3, 4])

In [10]:
a is b

False

In [11]:
np.shares_memory(a, b)

False

### `np.view` vs `np.copy`

#### `np.view()`

In [12]:
a = np.array([1, 2, 3, 4])
b = a.view()

a[1] = 100
b

array([  1, 100,   3,   4])

In [13]:
a is b

False

In [14]:
np.shares_memory(a, b)

True

#### `np.copy()`

In [15]:
a = np.array([1, 2, 3, 4])
b = a.copy()

a[1] = 100
b

array([1, 2, 3, 4])

In [16]:
a is b

False

In [17]:
np.shares_memory(a, b)

False

## Object Array

In [18]:
arr = np.array(
    [
        1,
        "Abcd",
        True,
        list([1, 2, 3]),
    ],
    dtype="object",
)
arr

array([1, 'Abcd', True, list([1, 2, 3])], dtype=object)

In [19]:
[type(item) for item in arr]

[int, str, bool, list]

In [20]:
a = np.array([0, 1, 2, 3, 4, 5])
b = a[a % 1 == 0]
b[0] = 10
a[:2]

array([0, 1])

## Spliting

### `np.split`

In [21]:
arr = np.arange(0, 8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [22]:
np.split(arr, 2)

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

In [23]:
try:
    np.split(arr, 3)

except ValueError as err:
    print(err)

array split does not result in an equal division


In [24]:
splits = np.split(arr, indices_or_sections=[2, 5, 7, 8, 100])
splits

[array([0, 1]),
 array([2, 3, 4]),
 array([5, 6]),
 array([7]),
 array([], dtype=int64),
 array([], dtype=int64)]

> **Note**:
>
> `indices_or_sections` accepts values out of range

In [25]:
type(splits)

list

In [26]:
arr = np.arange(1, 17).reshape(4, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [27]:
np.split(arr, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [28]:
np.split(arr, 2, axis=0)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [29]:
np.split(arr, 2, axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

### `np.vsplit`

### `np.hsplit`

## Stacking

### `np.vstack`

In [30]:
arr = np.arange(1, 4)
arr

array([1, 2, 3])

In [31]:
op = np.vstack((arr, arr))

display(op)
print("\nShape:", op.shape)

array([[1, 2, 3],
       [1, 2, 3]])


Shape: (2, 3)


In [32]:
arr = np.arange(1, 5).reshape(2, 2)
arr

array([[1, 2],
       [3, 4]])

In [33]:
op = np.vstack((arr, arr))

display(op)
print("\nShape:", op.shape)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])


Shape: (4, 2)


### `np.hstack`

In [34]:
arr = np.arange(1, 4)
arr

array([1, 2, 3])

In [35]:
op = np.hstack((arr, arr))

display(op)
print("\nShape:", op.shape)

array([1, 2, 3, 1, 2, 3])


Shape: (6,)


In [36]:
arr = np.arange(1, 5).reshape(2, 2)
arr

array([[1, 2],
       [3, 4]])

In [37]:
op = np.hstack((arr, arr))

display(op)
print("\nShape:", op.shape)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])


Shape: (2, 4)


In [38]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.hstack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [39]:
try:
    a = np.array([[1], [2], [3]])
    b = np.array([[4], [5], [6], [7]])
    np.hstack((a, b))

except ValueError as err:
    print(err)

all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4


### `np.concatenate`

In [49]:
arr = np.array([2, 4, 6, 8, 10])
c0 = arr
c0[0] = 12

arr = np.array([2, 4, 6, 8, 10])
c1 = arr.view()
arr[0] = 12
print(c1)

arr = np.array([2, 4, 6, 8, 10])
c2 = arr.copy()
arr[0] = 12
print(c2)

[12  4  6  8 10]
[ 2  4  6  8 10]


In [53]:
arr = np.arange(10)
np.split(arr, [5, 12])

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([], dtype=int64)]

In [55]:
arr = np.array(
    [
        [
            [0, 1],
            [2, 3],
        ],
        [
            [4, 5],
            [6, 7],
        ],
    ]
)
arr[:, 0:,:1]

array([[[0],
        [2]],

       [[4],
        [6]]])

array([ 2,  4,  6,  8, 10])

## Matrix

## Matrix Initialization

## Matrix Multiplication